// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBedLZZepkUOd8-nYngxSDbQgjmnCx62wg',
    appId: '1:737317154851:web:3165aba6845616f4998196',
    messagingSenderId: '737317154851',
    projectId: 'foodwastemanagement-82a1c',
    authDomain: 'foodwastemanagement-82a1c.firebaseapp.com',
    storageBucket: 'foodwastemanagement-82a1c.appspot.com',
    measurementId: 'G-PC4ZY8J18X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFgZrYwJzft2BODmJdM0nXQ3Jq8mFzpJg',
    appId: '1:737317154851:android:e9c1f7c2cf527036998196',
    messagingSenderId: '737317154851',
    projectId: 'foodwastemanagement-82a1c',
    storageBucket: 'foodwastemanagement-82a1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR7KcyyChVnAo_NvwQv68W5XMBX2TBFEk',
    appId: '1:737317154851:ios:196d22ee601fd0de998196',
    messagingSenderId: '737317154851',
    projectId: 'foodwastemanagement-82a1c',
    storageBucket: 'foodwastemanagement-82a1c.appspot.com',
    iosClientId: '737317154851-qojnghhtn9nf8hpcndlj26955m1gi7eo.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodWasteManagement',
  );
}
